name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main  # Déclencher le déploiement sur la branche `main`, ou celle de ton choix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Assurez-vous que le fichier kubeconfig est stocké dans GitHub Secrets

      - name: Update Helm repositories
        run: helm repo update

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install devops-autonomous ./charts/devops-autonomous -f ./charts/devops-autonomous/values.yaml --namespace default
